---

- name: Deploy Webserver Content and Configuration
  connection: ssh
  gather_facts: false
  hosts: 172.16.10.10
  vars:
    repo_folder: https://github.com/Kjento/IaC-Challenge/application
    live_folder: /home/www
    repo_name: Kjento/IaC-Challenge
  tasks:
  
  # - git:
      # repo: https://git@github.com/Kjento/IaC-Challenge.git
      # dest: /home/webserver/www
      # update: no