---

- name: Deploy Webserver Content and Configuration
  connection: ssh
  gather_facts: false
  hosts: 172.16.10.10
  vars:
    repo_folder: https://github.com/Kjento/IaC-Challenge/application
    live_folder: /home/www
    repo_name: Kjento/IaC-Challenge
  tasks:
  - name: Clean old webserver content folder
    file:
      path: /usr/share/nginx/html/
      state: absent
    become: yes
  - name: Create webserver content folder
    file:
      path: /usr/share/nginx/html/
      state: directory
    become: yes
  - name: Download webserver content from 'IaC-Jenkins-CentOS' server
    copy:
      src: /tmp/iac_github/application/
      dest: /usr/share/nginx/html/
      mode: '0755'
    become: yes
  - name: Install nginx webserver
    yum:
      name: nginx
      state: present
  - name: Start nginx webserver
    service:
      name: nginx
      state: started
      enabled: yes