---

- name: Deploy React App Front-end Build
  connection: ssh
  gather_facts: false
  hosts: localhost
  vars:
    repo_folder: https://github.com/Kjento/IaC-Challenge
    live_folder: /home/www
    repo_name: Kjento/IaC-Challenge
  tasks:
  - name: Fix 'support_tools' permissions
      file: path=/home/www owner=Luca group=Luca mode=0775 state=directory recurse=yes
  - git:
      repo: ssh://git@github.com/Kjento/IaC-Challenge.git
      dest: /home/www
      update: yes