---

- name: Deploy React App Front-end Build
  connection: ssh
  gather_facts: false
  hosts: localhost
  vars:
    repo_folder: https://github.com/Kjento/IaC-Challenge
    live_folder: /home
    repo_name: Kjento/IaC-Challenge
  tasks:
    - git:
      repo: ssh://git@github.com/Kjento/IaC-Challenge.git
      dest: /home/Luca/hello