---

- name: Deploy React App Front-end Build
  connection: ssh
  gather_facts: false
  hosts: localhost
  vars:
    repo_folder: /var/www/github-deployment/repos/
    live_folder: /var/www/my_app/build
    repo_name: Kjento/IaC-Challenge
  tasks:
    - git:
        repo: ssh://git@github.com/Kjento/IaC-Challenge.git
        dest: "https://github.com/Kjento/IaC-Challenge/tree/main/application"
        update: yes
   - name: Install dependencies
      yarn:
        path: "https://github.com/Kjento/IaC-Challenge/tree/main/application"
   - name: Build project
      command: yarn build
      args:
        chdir: "https://github.com/Kjento/IaC-Challenge/tree/main/application"
    
   - name: Copy build to live directory
      command: cp -TRv build /var/www/my_app/build
      args:
        chdir: "https://github.com/Kjento/IaC-Challenge/tree/main/application"