- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: RG-IaC
      allocation_method: Static
      name: myPublicIPv4
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: RG-IaC
      name: IaC_Webserver_NIC
      virtual_network: RG-IaC-vnet
      subnet: default
      public_ip_name: myPublicIP
      security_group: IaC-Jenkins-CentOS-nsg
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: RG-IaC
      name: IaC_Webserver
      vm_size: Standard_B1s
      admin_username: wklc_admin
      ssh_password_enabled: false
      ssh_public_keys: 
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest