IaC-jenkins-CentOS:
  resource_group: RG-IAC
  name: testvm10
  hosts: localhost
  vm_size: Standard_B1
  admin_username: WKLC Admin
  ssh_password_enabled: false
  ssh_public_keys: "{{ ssh_keys }}"
  image:
    offer: CentOS
    publisher: OpenLogic
    sku: '7.1'
    version: latest
