- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: RG-IaC
      name: IaC_Webserver
      vm_size: Standard_B1s
      admin_username: wklc_admin
      ssh_password_enabled: false
      ssh_public_keys:
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest