---

- name: Create Azure IaC Resources
  hosts: localhost
  connection: local
  tasks:
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: RG-IaC
      domain_name: iac-wklc-web
      allocation_method: Static
      name: IaC-Webserver-Public-IPv4
  - name: Create security group that allows SSH
    azure_rm_securitygroup:
      resource_group: RG-IaC
      name: IaC-Webserver-nsg
      rules:
      - name: Allow_VM_traffic_inbound
        protocol: Tcp
        destination_port_range:
        - 22
        - 80
        - 443
        access: Allow
        priority: 100
        direction: Inbound
  - name: Create virtual network interface for webserver
    azure_rm_networkinterface:
      name: IaC-Webserver-NIC
      resource_group: RG-IaC
      virtual_network: RG-IaC-vnet
      subnet_name: default
      ip_configurations:
      - name: ip01
        private_ip_address: 172.16.10.10
        private_ip_allocation_method: Static
        public_ip_address_name: IaC-Webserver-Public-IPv4
        primary: True
      security_group: IaC-Webserver-nsg
  - name: Create Webserver VM
    azure_rm_virtualmachine:
      resource_group: RG-IaC
      name: IaC-Webserver
      vm_size: Standard_B1s
      network_interfaces: IaC-Webserver-NIC
      admin_username: wklc-admin
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/wklc-admin/.ssh/authorized_keys
          key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCtSqlY5+gyVMdu+wVTPpIfVYIYPcJE9UxVJm1UhBYf43ZGF9e/O5z7Hu0urJEOPN+PWT6HdpHNHadmumorH/dnNaLlQJlVJ+OxEmmUcTXAmnuokekzxZd/vl1y7wiHUQRiPLVN8lW3k8AMf9uOu46W96iRtERwRMHtIa8DXkNLrUdPmdn6Wo6wfEtDRFa4/FZPCDI2UramqSBLgIxBwgEuHe0G6MlvEPZf3BV5E0IlXt3uuq3rGoelWtXMc1EQTJQOxSFm7H0JCh/9pDzMumV124JFYKs2E2JnEx76vNjmqGHSNox7ChHHpVBPnGQqJuUGeBXdPaQ2FuMbhvpmOhO/a+12it67hWPJLrkPumLdVUR005F+HG+P4XA9fvjjTaZpQkONgsgHozbqk29rY4E69N/zZDiJSoNRS+gVEmXoWj9guCbX+wxX50KEHk6nBl2y0kZ5b/2mSQraF5DZ1fUgV9KxMxPxFz+/cLoMkyGpfsgEbv1h937SX17ewyHEiQU="
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest