azure_rm_virtualmachine:
  resource_group: RG-IaC
  name: testvm10
  hosts: localhost
  vm_size: Standard_B1
  admin_username: WKLC Admin
  ssh_password_enabled: false
  ssh_public_keys: "{{ ssh_keys }}"
  image:
    offer: CentOS
    publisher: OpenLogic
    sku: '7.1'
    version: latest
