---

- name: Create Azure VM
  hosts: localhost
  connection: local
  environment:
    AZURE_SUBSCRIPTION_ID=c8cb63f5-3f5d-4787-868f-3ee4ce95b17e
    AZURE_TENANT=77d33cc5-c9b4-4766-95c7-ed5b515e1cce
    AZURE_SECRET=Rr1234-56789
    AZURE_CLIENT_ID=fb6b5c1c-7305-4699-bf54-ac230c4e3370
  tasks:
  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: RG-IaC
      allocation_method: Static
      name: myPublicIPv4
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: RG-IaC
      name: IaC_Webserver_NIC
      virtual_network: RG-IaC-vnet
      subnet: default
      public_ip_name: myPublicIP
      security_group: IaC-Jenkins-CentOS-nsg
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: RG-IaC
      name: IaC_Webserver
      vm_size: Standard_B1s
      admin_username: wklc_admin
      ssh_password_enabled: false
      ssh_public_keys: 
      image:
        offer: CentOS
        publisher: OpenLogic
        sku: '7.5'
        version: latest