---
# Groep 7 | Wouter Bosmans, Kjento Lauwers, Luca Claes, Cédric Gijsels

- name: Download content from GitHub Application folder
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Remove old GitHub local content folder
    file:
      path: /tmp/iac_github/
      state: absent 
  - name: Create GitHub local content folder
    file:
      path: /tmp/iac_github/
      state: directory
  - name: Download GitHub repository (checkout)
    git:
       repo: ssh://git@github.com/Kjento/IaC-Challenge.git
       dest: /tmp/iac_github/
       key_file: /var/iac-github.key
 