---

- name: Download content from GitHub Application folder
  hosts: localhost
  connection: local
  tasks:
  - name: Create Webserver Content Folder
    command: mkdir /home/wwwroot/
    become: true
    become_user: root
  - name: GitHub checkout (download content)
    git:
       repo: https://git@github.com/Kjento/IaC-Challenge.git
       dest: /home/Luca/wwwroot
