---

- name: Download content from GitHub Application folder
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Create Webserver Content Folder
    file:
      path: /tmp/iac_wwwroot/
      state: directory
  - name: GitHub checkout (download content)
    git:
       repo: ssh://git@github.com/Kjento/IaC-Challenge.git
       dest: /tmp/iac_wwwroot/
       update: yes
       key_file: /tmp/ssh5315902378920631758.key
 